"""empty message

Revision ID: 65d3fb9cf289
Revises: f3e47ff093bc
Create Date: 2018-07-26 20:03:39.875078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d3fb9cf289'
down_revision = 'f3e47ff093bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mentees', 'mentee_email',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('mentees', 'mentee_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_constraint('mentees_mentee_name_key', 'mentees', type_='unique')
    op.create_unique_constraint(None, 'mentees', ['mentee_email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mentees', type_='unique')
    op.create_unique_constraint('mentees_mentee_name_key', 'mentees', ['mentee_name'])
    op.alter_column('mentees', 'mentee_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('mentees', 'mentee_email',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###
