"""empty message

Revision ID: f3e47ff093bc
Revises: d98e2d78f083
Create Date: 2018-07-26 18:34:29.363401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e47ff093bc'
down_revision = 'd98e2d78f083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mentees_mentee_email_key', 'mentees', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('mentees_mentee_email_key', 'mentees', ['mentee_email'])
    # ### end Alembic commands ###
